spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:WARN}
    com.codersole.knowledgeserver: ${LOG_LEVEL_APP:INFO}
management:

  endpoints:

    web:

      exposure:

        include: health,info

  endpoint:

    health:

      show-details: never